let context = {
"Adult":"||/facebooksex.^",
"Business":"||-google-ad.^\n||-google-ads-^\n||-google-ads/^\n||-google-adsense.^\n||-google2-ad-^\n||-NewStockAd-^\n||/carouselads.^\n||/carsadtaggenerator.js^\n||/cashad.^\n||/cashad2.^\n||/category-sponsorship/^\n||/images/sponsored/^",
"Computer":"",
"Education":"||/googleadhp.^||/googleadhpbot.^||/googleadhtml/^||/googleadiframe_^||/googleadright.^||/googleads-^||/googleads.^||/googleads/^||/googleads1.^||/googleads2.^||/googleads3widetext.^||/googleads_^||/googleadsafc_^||/googleadsafs_^||/googleAdScripts.^||/googleadsense.^||/googleAdTaggingSubSec.^||/googleadunit^||/googleafc.^||/googleafs.^||/googleafvadrenderer.^||/googlecontextualads.^||/GoogleDFP.^||/googleheadad.^||/googleleader.^||/googleleads.^||/googlempu.^||/google-ad-^||/google-ad?^||/Google-Ads-^||/google-ads.^||/google-ads/*^||/google-adsense-^||/google-adsense.^||/google-adverts-^||/google-adwords^||/google-afc-^||/google-afc.^||/google/ad?^||/google/adv.^||/google160.^||/google728.^||/google_ad.^||/google_ad_^||/google_ads.^||/google_ads/*^||/google_ads_^||/google_adv/*^||/google_afc.^||/google_afc_^||/google_afs.^||/google_afs_widget/^||/google_caf.js^||/google_lander2.js^||/google_radlinks_^||/googlead-^||/googlead.^||/googlead1.^||/googlead160.^||/GoogleAd300.^||/googlead336x280.^||/googlead_^||/googleadarticle.^||/GoogleAdBg.^||/googleadcode.^||/googleaddfooter.^||/googleaddisplayframe.^||/campaign/advertiser_^||/campus/ads/^",
"Entertainment":"||-gallery_ad/^\n||/facebookaff/^\n||/facebookaff2/^\n||/facebooksex.^",
"Games":"||/gam.html^\n||/gam_ad.^\n||/gam_ad_^\n||/gam_ads.^\n||/gamads/^\n||/game-ads.^\n||/gamead/^\n||/gameadsync.^\n||/gamersad.^\n||/games_ad_^\n||-games/ads/^",
"Health":"||-feed-ads.^\n||-fleshlight2.^",
"Home":"",
"Kids":"",
"Media":"||-NewAd.^\n||-news-ad-^\n||-newsletter-ad^",
"Shopping":"||-featured-ads.^||-featured-ads/^||.tv/adl.^||.tv/ads.^||.tv/ads/^||/buyad.^||||/buyclicks/*^||/buyer/dyad/*^||/buysellads-^||/buysellads.^||/deliver.jphp?^||/deliver.nmi?^||/deliver/wr^||/deliverad/^||/deliverads.^||/deliverjs.nmi^||/deliversd/^||/deliversds.^||/delivery.ads.^||/delivery.php?pool_id=^||/delivery.php?rnd=^||/delivery/*?advplaces=^||/delivery/afr.^||/delivery/ag.^||/delivery/al.php^||/delivery/apu.php^||/delivery/avw.^||/delivery/fc.^||/delivery/fl.^||/delivery/hb.php^||/delivery/spc.^||/delivery/vbafr.php^||/delivery_ads/^||/ebay_ads/^||/ebayad.^||/image/sponsors/^||/images/gads_^||/images/sponsored.^",
"Sports":""
};
contextList={
  0:"Adult",
  1:"Business",
  2:"Computer",
  3:"Education",
  4:"Entertainment",
  5:"Games",
  6:"Health",
  7:"Home",
  8:"Kids",
  9:"Media",
  10:"Shopping",
  11:"Sports"
};
